repo: 'icon-cards'
canvasCourse: 'web-dev-3'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    valid: true
    bestPractices: true
    has:
      - ['link[href*="modules.css"] + link[href*="grid.css"]', 'The `modules.css` file must come before the `grid.css` file']
      - ['link[href*="grid.css"] + link[href*="type.css"]', 'The `grid.css` file must come before the `type.css` file']
      - ['link[href*="type.css"] + link[href*="main.css"]', 'The `type.css` file must come before the `main.css` file']
      - '.grid'
      - '.grid > .unit'
      - 'img[src*="placeholder-hex.svg"]'
      - '.card'
      - '.btn.btn-ghost'
      - '.icon'
    search:
      - 'xs-'
      - 's-'
      - 'm-'
      - 'l-'
      - 'push-?'
      - 'island-?'
      - 'micro|milli|kilo|mega|giga|tera|peta|exa|zetta|yotta'
      - 'i-'
      - 'Human Paladin'
      - 'Dedicated to the everlasting oath of honour, justice and goodness.'
      - 'Choose Paladin'
      - 'Drow Rogue'
      - 'A near invincible killer who’s craft was honed in the dark caves.'
      - 'Choose Rogue'
      - 'Wood Elf Ranger'
      - 'A rugged individualist who survives on wits, will and muscle.'
      - 'Choose Ranger'

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true
    has:
      - ['html', 'font-family', 'sans-serif']
      - ['.card']
    search:
      - '#fff'
      - '#e6e6e6'
      - '#333'
      - '#000'
      - 'background-color'
      - 'border-radius'
      - 'color'
      - 'border'
      - 'text-decoration'
    search_not:
      - 'padding'
      - 'margin'
      - 'font-size'
  - path: 'css/grid.css'
    valid: true
    bestPractices: true
    search:
      - ['https://gridifier.web-dev.tools/#xs,4,0,0,0;s,4,25,0,0;m,4,38,1,1;l,4,60,1,1', 'The `grid.css` should be generated with Gridifier’s default settings']
  - path: 'css/type.css'
    valid: true
    bestPractices: true
    search:
      - ['https://typografier.web-dev.tools/#0,100,1.3,1.067,0;38,110,1.4,1.125,1;60,120,1.5,1.125,1;90,130,1.5,1.125,1', 'The `type.css` should be generated with Typografier’s default settings']
  - path: 'css/modules.css'
    valid: true
    bestPractices: true
    search:
      - ['https://modulifier.web-dev.tools/#responsive;images;list-group;embed;media-object;icons;hidden;positioning;nice-lists;buttons;forms;accessibility;print', 'Select all the different modules when adding Modulifier.']

screenshots:
  - path: 'index.html'
    sizes: [320, 400, 608, 960, 1440]

functionality:
  - path: 'index.html'
    tests:
      - |
        let link = $('.card');
        let oldBg = css(link).backgroundColor;

        hover('.card', function () {
          if (css(link).backgroundColor == oldBg) fail('The background colour of the `.card` doesn’t change when hovered')
          pass();
        });
